title: Torch June default configuration file.

system:
  device: cpu
  random_seed: random

save_path: ./results/june
age_bins_to_save: [0, 18, 25, 65, 100]

data_path: /Users/arnull/code/gradabm-june/worlds/camden_leisure_1.pkl

timer:
  initial_day: '2020-03-01'
  step_activities:
    weekday:
      0:
       - company
       - school
         #- pub
         #- university
         #- grocery
         #- gym
         #- cinema
         #- visit
         #- care_visit
         #- care_home
       - household
    weekend:
      0:
        #- pub
        #- grocery
        #- gym
        #- cinema
        #- visit
        #- care_visit
        #- care_home
       - household 
  step_duration:
    weekday:
      0: 24
    weekend:
      0: 24
  total_days: 65

networks:
  household:
    log_beta: 0.5 
  company:
    log_beta: 0.5 
  school:
    log_beta: 0.5
  university:
    log_beta: 0.5 
  pub:
    log_beta: 0.5 
  grocery:
    log_beta: 0.5
  gym:
    log_beta: 0.5
  visit:
    log_beta: 0.5
  cinema:
    log_beta: 0.5
  care_visit:
    log_beta: 0.5
  care_home:
    log_beta: 0.5

infection_seed:
  log_fraction_initial_cases: -3.5

leisure:
  care_visit:
    weekday:
      female:
        0-65: 0.0
        65-75: 0.25
        75-100: 0.5
      male:
        0-65: 0.0
        65-75: 0.25
        75-100: 0.5
    weekend:
      female:
        0-65: 0.0
        65-75: 0.25
        75-100: 0.5
      male:
        0-65: 0.0
        65-75: 0.25
        75-100: 0.5
  cinema:
    weekday:
      female:
        0-9: 0.0224
        15-19: 0.0198
        19-31: 0.0066
        31-51: 0.0028
        51-66: 0.0062
        66-86: 0.0016
        86-100: 0.0
        9-15: 0.0066
      male:
        0-9: 0.0
        15-19: 0.0012000000000000001
        19-31: 0.0032
        31-51: 0.0018
        51-66: 0.0018
        66-86: 0.003
        86-100: 0.0
        9-15: 0.0054
    weekend:
      female:
        0-9: 0.0165
        15-19: 0.007
        19-31: 0.006
        31-51: 0.0055
        51-66: 0.005
        66-86: 0.004
        86-100: 0.0
        9-15: 0.007
      male:
        0-9: 0.0095
        15-19: 0.0
        19-31: 0.0
        31-51: 0.0045
        51-66: 0.002
        66-86: 0.005
        86-100: 0.0
        9-15: 0.0065
  grocery:
    weekday:
      female:
        0-9: 0.0472
        15-19: 0.0648
        19-31: 0.0984
        31-51: 0.124
        51-66: 0.16299999999999998
        66-86: 0.0492
        86-100: 0.0182
        9-15: 0.0526
      male:
        0-9: 0.028599999999999997
        15-19: 0.043
        19-31: 0.0534
        31-51: 0.0762
        51-66: 0.079
        66-86: 0.0392
        86-100: 0.013000000000000001
        9-15: 0.0392
    weekend:
      female:
        0-9: 0.0555
        15-19: 0.095
        19-31: 0.1145
        31-51: 0.133
        51-66: 0.1405
        66-86: 0.1145
        86-100: 0.075
        9-15: 0.0995
      male:
        0-9: 0.0535
        15-19: 0.0555
        19-31: 0.087
        31-51: 0.1005
        51-66: 0.1225
        66-86: 0.0875
        86-100: 0.041
        9-15: 0.057
  gym:
    weekday:
      female:
        0-9: 0.08080000000000001
        15-19: 0.033600000000000005
        19-31: 0.0426
        31-51: 0.036
        51-66: 0.0368
        66-86: 0.0072
        86-100: 0.0021999999999999997
        9-15: 0.07339999999999999
      male:
        0-9: 0.0248
        15-19: 0.11739999999999999
        19-31: 0.0804
        31-51: 0.0548
        51-66: 0.0536
        66-86: 0.0206
        86-100: 0.0038
        9-15: 0.046200000000000005
    weekend:
      female:
        0-9: 0.037
        15-19: 0.022
        19-31: 0.0335
        31-51: 0.0385
        51-66: 0.0205
        66-86: 0.0155
        86-100: 0.002
        9-15: 0.066
      male:
        0-9: 0.0925
        15-19: 0.1185
        19-31: 0.0725
        31-51: 0.065
        51-66: 0.073
        66-86: 0.0445
        86-100: 0.0
        9-15: 0.095
  pub:
    weekday:
      female:
        0-9: 0.027000000000000003
        15-19: 0.0716
        19-31: 0.10880000000000001
        31-51: 0.08
        51-66: 0.0818
        66-86: 0.020200000000000003
        86-100: 0.004
        9-15: 0.0294
      male:
        0-9: 0.0064
        15-19: 0.0252
        19-31: 0.1476
        31-51: 0.0842
        51-66: 0.1066
        66-86: 0.03
        86-100: 0.0066
        9-15: 0.0212
    weekend:
      female:
        0-9: 0.0215
        15-19: 0.0705
        19-31: 0.1255
        31-51: 0.1155
        51-66: 0.09
        66-86: 0.073
        86-100: 0.03
        9-15: 0.0405
      male:
        0-9: 0.019
        15-19: 0.053
        19-31: 0.1605
        31-51: 0.131
        51-66: 0.152
        66-86: 0.088
        86-100: 0.0315
        9-15: 0.0505
  visit:
    weekday:
      female:
        0-9: 0.4662
        15-19: 0.5236
        19-31: 0.274
        31-51: 0.146
        51-66: 0.219
        66-86: 0.2226
        86-100: 0.0646
        9-15: 0.3196
      male:
        0-9: 0.4624
        15-19: 0.324
        19-31: 0.2764
        31-51: 0.1258
        51-66: 0.1638
        66-86: 0.1598
        86-100: 0.09459999999999999
        9-15: 0.343
    weekend:
      female:
        0-9: 0.7425
        15-19: 0.6075
        19-31: 0.518
        31-51: 0.259
        51-66: 0.2585
        66-86: 0.2235
        86-100: 0.101
        9-15: 0.657
      male:
        0-9: 0.562
        15-19: 0.505
        19-31: 0.4375
        31-51: 0.222
        51-66: 0.228
        66-86: 0.183
        86-100: 0.0745
        9-15: 0.5535

symptoms:
  recovery_times:
    critical:
      dist: LogNormal
      loc: 2.8387344001307495
      scale: 0.3381642741066263
    exposed:
      dist: LogNormal
      loc: 1.4513971389473608
      scale: 0.32459284597450133
    infectious:
      dist: LogNormal
      loc: 2.0491292307716185
      scale: 0.24622067706923975
    severe:
      dist: LogNormal
      loc: 2.8387344001307495
      scale: 0.3381642741066263
    symptomatic:
      dist: LogNormal
      loc: 2.0491292307716185
      scale: 0.24622067706923975
  stage_transition_probabilities:
    critical:
      0-10: 1.0
      10-20: 1.0
      20-30: 1.0
      30-40: 1.0
      40-50: 1.0
      50-60: 1.0
      60-70: 1.0
      70-80: 1.0
      80-90: 1.0
      90-100: 1.0
    exposed:
      0-100: 1.0
    infectious:
      0-10: 0.5
      10-20: 0.55
      20-30: 0.6
      30-40: 0.65
      40-50: 0.7
      50-60: 0.75
      60-70: 0.8
      70-80: 0.85
      80-90: 0.9
      90-100: 0.9
    recovered:
      0-100: 0.0
    severe:
      0-10: 1.0
      10-20: 1.0
      20-30: 1.0
      30-40: 1.0
      40-50: 1.0
      50-60: 1.0
      60-70: 1.0
      70-80: 1.0
      80-90: 1.0
      90-100: 1.0
    susceptible:
      0-100: 0.0
    symptomatic:
      0-10: 7.0e-06
      10-20: 3.3e-05
      20-30: 0.000141
      30-40: 0.000546
      40-50: 0.002041
      50-60: 0.04586
      60-70: 0.097496
      70-80: 0.224919
      80-90: 0.28688
      90-100: 0.392194
  stage_transition_times:
    critical:
      dist: LogNormal
      loc: 2.278566445372413
      scale: 0.42819924356646805
    exposed:
      dist: LogNormal
      loc: 1.4513971389473608
      scale: 0.32459284597450133
    infectious:
      dist: LogNormal
      loc: -0.16092839609790693
      scale: 0.7158750951139896
    severe:
      dist: LogNormal
      loc: -0.10536051565782628
      scale: 1.0107676525947895
    symptomatic:
      dist: LogNormal
      loc: 1.667557249282718
      scale: 0.6625894652794622
  stages:
  - recovered
  - susceptible
  - exposed
  - infectious
  - symptomatic
  - severe
  - critical
  - dead
transmission:
  max_infectiousness:
    dist: LogNormal
    loc: 0.0
    scale: 0.5
  rate:
    dist: Normal
    loc: 0.53
    scale: 0.03
  shape:
    dist: Normal
    loc: 1.56
    scale: 0.08
  shift:
    dist: Normal
    loc: -2.12
    scale: 0.1
